[directory]
truncation_length=8
fish_style_pwd_dir_length=1

[aws] #display everything
format = 'on [$symbold($profile )(\($region\) )]($style)'
style = "bold blue"
[aws.region_aliases]
ap-southeast-3 = "au"
us-east-2 = "va"

[docker_context]
format = "via [ğŸ‹ $context](bule bold)"
